---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Tutorials
- type: directory
  path: java
  label: Java Tutorial
  create: all
  match: java/*
  templates:
  - documentation-page
- type: heading
  label: Content
- type: directory
  path: docs
  label: Scala Tutorials
  create: all
  match: scala/*
  templates:
  - documentation-page
- type: heading
  label: Settings
- type: document
  path: data/settings.json
  label: Menu
upload_dir: static
public_path: "/docs"
front_matter_path: "/docs"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn develop
